import Head from 'next/head'
import Header from "@/components/header";
import Banner from "@/components/banner";
import Mission from "@/components/mission";
import Featured from "@/components/featured";
import Reviews from "@/components/reviews";
import Products from "@/components/product";

export default function Home({ pageData }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Header />
                <br />
                <br />
                <br />

                <br />
                <Banner
                    heroText={pageData?.hero_section_text}
                    heroImgUrl={pageData?.hero_section_image}
                />

                <br />
                <Mission
                    missionImgUrl={pageData?.mission_section_image}
                    missionText={pageData?.mission_section_text} />
                <br />
                <Featured products={pageData?.product_collections} />
                <br />
                <Products products={pageData?.product_collections} />
                <br />
                <Reviews reviews={pageData?.customer_reviews} />

            </main>
        </>
    )
}

export async function getStaticProps({locale}) {
    const BUTTERCMS_READ_KEY = process.env.BUTTERCMS_READ_KEY
    const BUTTERCMS_BASE_URL = process.env.BUTTERCMS_BASE_URL
    const BUTTERCMS_COLLECTION_SLUG = process.env.BUTTERCMS_COLLECTION_SLUG

    if (
        !BUTTERCMS_READ_KEY ||
        !BUTTERCMS_BASE_URL ||
        !BUTTERCMS_COLLECTION_SLUG
    ) throw new Error("BUTTERCMS CREDENTIALS ARE MISSING!!!")

    try {
        const req = await fetch(`${BUTTERCMS_BASE_URL}/content/${BUTTERCMS_COLLECTION_SLUG}?locale=${locale}`, {
            headers: {
                "Authorization": `Token ${BUTTERCMS_READ_KEY}`
            }
        })

        const { data } = await req.json()

        return {
            props: {
                pageData: data?.ecommerce_brand_page[0]
            }
        }
    } catch (e) {
        console.log(e)

        return {
            props: {}
        }
    }


}